# Generated by Django 3.2 on 2022-05-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
